### ISSUE TITLE
session token in the code 

### ISSUE THREAD

**Issue by alexanderkjeldaas** [barnesoir/chatgpt-vscode-plugin#1]
There is a session token in https://github.com/barnesoir/chatgpt-vscode-plugin/blob/main/src/extension.ts#L40

You can use ChatGPT to rewrite the code so it imports this using dotenv.

**Comment by barnesoir** [comment]
Cheers for that, was just a temp measure in the mean time, updating the plug in now to take it from a window.

**Comment by barnesoir** [comment]
Fixed in this commit, allowing loading and storing sessionToken.
https://github.com/barnesoir/chatgpt-vscode-plugin/commit/bfa189da3251fe9ec96f7fbcb9e5f245a57376fb
