### ISSUE TITLE
reset token does not work

### ISSUE THREAD

**Issue by alexanderkjeldaas** [barnesoir/chatgpt-vscode-plugin#11]
The view does conditional setup of the token so it will not catch that it was reset.  Better to do this unconditionally.

```
        // Initialize session token and ChatGPT API if not done already
        if (!this.sessionToken) {
            await this.setUpSessionToken();
        }
```

**Comment by barnesoir** [comment]
Good spot

https://github.com/barnesoir/chatgpt-vscode-plugin/commit/42de560920f0a479600f19de2614253440ca06fd
