### ISSUE TITLE
License / credit original code

### ISSUE THREAD

**Issue by gencay** [barnesoir/chatgpt-vscode-plugin#12]
Hi there,

I couldn't find any of your contact information so creating an issue here.

I stumbled upon this repo while developing my chatgpt extension and noticed incredible similarities between what I built and your work. I'm happy you liked my chatgpt conversation UX and you copied over to your extension. It's cool to see adoption in open source! I haven't tried your extension yet but the screenshot you have on the marketplace resembles mine a lot and I can see a lot of my original code in your repo as well without any credits.

As I've put in so many sleepless hours and days on what I built, I'd appreciate if you could respect the license and add proper credits wherever you want to use/modify original code. You can find the license here: https://github.com/gencay/vscode-chatgpt

**Comment by barnesoir** [comment]
Hi @gencay thanks for reaching out <3
Yeah I ported the conversation UX you did and merged it with https://github.com/mpociot/chatgpt-vscode.
I've added both extensions to the README
