### ISSUE TITLE
Would you like to add a function to reset thread like on the website?

### ISSUE THREAD

**Issue by LRLVEC** [barnesoir/chatgpt-vscode-plugin#16]
As the title mentioned.

**Comment by dchiquito** [comment]
Currently, conversations are not tracked, so the thread is implicitly reset every time. The appearance of the chat history implies otherwise, which is misleading. If #21 (conversation support) is merged then there will be a `ChatGPT: Reset thread` command.

**Comment by LRLVEC** [comment]
Thanks!
