### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by astolfobaka** [barnesoir/chatgpt-vscode-plugin#17]
![image](https://user-images.githubusercontent.com/59239496/206384895-9f2f3a2b-2e8d-4856-a31b-ac2e1a5efc67.png)

**Comment by qq5625655** [comment]
+1   
 I had the same problem

**Comment by dchiquito** [comment]
This happened to me when my session expired and the ChatGPT service was down due to excessive load. I think the problem is most likely with ChatGPT itself, not the plugin.

**Comment by barnesoir** [comment]
This can happen when your session expires or ChatGPT is having network issues.
ChatGPT is still in very early beta stages and are facing some scaling issues with the general interest in openai.
I'd recommend logging in again in the plugin, this will be resolved once an official API is out
