### ISSUE TITLE
Can you or someone explain this more easily for me? For example with chrome

### ISSUE THREAD

**Issue by Marco-Don** [barnesoir/chatgpt-vscode-plugin#26]
![image](https://user-images.githubusercontent.com/114935066/207473361-be61266e-8e67-4b72-a91c-a5820801cd35.png)

**Comment by barnesoir** [comment]
@Marco-Don I'll add a more in depth instructions later today

**Comment by KKQQ** [comment]
I just want to know what's the sixth step?? I can't find the 'user-agent' or 'Request Headers'. What's that? Thank you!

**Comment by Marco-Don** [comment]
@KKQQ 
Go to the 'Network' section/tab -> (Refresh the page if necessary if everything under 'Name' is empty) -> Then select one of all by clicking -> 'Headers' has opened, and scroll down to the very bottom Go to the 'Request Headers' section -> then copy the value at the bottom under 'user-agent'.

Can you tell me if it worked for you? Because after all this, in visual studio code, I get an error after calling chatgpt..

**Comment by KKQQ** [comment]
> @KKQQ Go to the 'Network' section/tab -> (Refresh the page if necessary if everything under 'Name' is empty) -> Then select one of all by clicking -> 'Headers' has opened, and scroll down to the very bottom Go to the 'Request Headers' section -> then copy the value at the bottom under 'user-agent'.
> 
> Can you tell me if it worked for you? Because after all this, in visual studio code, I get an error after calling chatgpt..

I just figure out what that is and fill in. But I found a new error 'ChatGPT failed to refresh auth token. Error: 403 forbidden.' It seems ChatGPT just added the Cloudflare protection? How to fix this problem? Thank you!

**Comment by DavidRavnsborg** [comment]
I didn't have much difficulty following the guide - doing this to grab my SSO token for development and testing of React App I'd worked on was something I used to do every day - but I also keep encountering the error: "ChatGPT failed to refresh auth token. Error: 403 forbidden."

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.
