### ISSUE TITLE
ChatGTP failed to refresh auth token 403

### ISSUE THREAD

**Issue by 1013461195** [barnesoir/chatgpt-vscode-plugin#27]
from https://chat.openai.com/chat cookie get token , but not refresh auth token
![截屏2022-12-16 11 08 54](https://user-images.githubusercontent.com/23392657/208013164-2b02e99d-efb5-47d4-8ec6-f2fb0cdca83c.png)

**Comment by Akshay-Arjun** [comment]
Same! Any solution?

**Comment by aumirza** [comment]
I was facing the same issue, I fixed it by using reload option in command pallete.

**Comment by DavidRavnsborg** [comment]
> I was facing the same issue, I fixed it by using reload option in command pallete.
Do you mean "Reset token" option?

I've tried resetting my 3 tokens multiple times now (just in-case I was missing a section of one when I copied+pasted), but I still keep encountering this 403 error.

**Comment by DavidRavnsborg** [comment]
> I was facing the same issue, I fixed it by using reload option in command pallete.

I keep encountering the same issue, despite using "ChatGPT: Reset token" to refresh my 3 tokens.

**Comment by DavidRavnsborg** [comment]
I have now tried this using **Chrome**, **Firefox**, **Edge**, and **Brave** browsers with an associated SSO account. I also created a new account, signed in without using the SSO option, on the Brave browser. I encounter this same issue every time.

**Comment by DavidRavnsborg** [comment]
I updated to node v18.12.1 and am still encountering the same issue (an old version of node was implicated in one of the closed issues about this 403 error). Used the Brave browser.

E.g. useragent key-value pair:
user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

**Comment by Agrover112** [comment]
Same here guys

**Comment by jcfigueiredo** [comment]
bump

**Comment by ArmandoShala** [comment]
Same here, guys

**Comment by marcelloh** [comment]
same here

**Comment by raulbethencourt** [comment]
Same here, guys

**Comment by CodeMilo-py** [comment]
Sameeeeeeeeeee

**Comment by DanielCalle** [comment]
Same here

**Comment by fMoro1999** [comment]
Same 😢

**Comment by raulbethencourt** [comment]
Hi every body I'm using neovim also, and i was tying to use chatgpt plugin there aswell and i'have problems to make it work aswell. The answer that I was getting is that I don't have enough credits in my chatgpt account. Any way it's wierd also coz I've check it and I didn't use anything but maybe this lead can help someone.

**Comment by zimplexing** [comment]
same here

**Comment by imajinyun** [comment]
same here

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.

**Comment by RunningCoderLee** [comment]
> Fixed using official API in v2 release.

Where can I download v2 version?
