### ISSUE TITLE
error 429

### ISSUE THREAD

**Issue by jumper-d-1981** [barnesoir/chatgpt-vscode-plugin#29]
I was getting the 403 issue, resolved and was able to use chatGPT for about 4 minutes then started getting ChatGPTAPI error 429.

Any one have any thoughts on this?

I tried reloading and closing and reopening.  Nada.

TY.

**Comment by FrancescoMussi** [comment]
Same here.
The plugin worked the first time only.
Afterwards getting **error 429**: `Error sending request to ChatGPT`.
Clicking the button doesn't do anything.
Any idea how to solve this?

<img width="478" alt="Screenshot 2022-12-26 at 21 54 47" src="https://user-images.githubusercontent.com/5312907/209579855-58597b78-4550-42dc-ac6c-65c5cb70b3ea.png">

**Comment by rjohnson318** [comment]
same here

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.
