### ISSUE TITLE
Feature requestion: History or Conversation View

### ISSUE THREAD

**Issue by tarasglek** [barnesoir/chatgpt-vscode-plugin#3]
Loving this extension for refactoring. Thanks for the quick doc-fix.

It would be helpful to maintain a history of questions, responses. This way as a dev I see history of my interactions:
* so I can cherry pick best parts of suggestions from multiple solutions.
* also so I can easier take screenshots of successful interactions to share with coworkers/socials
* if this was kept as a gptchat session history, it would also give gpt more context. Would be cool to keep that history per-project. but still have a way to reset it.
* Alternatively, would be helpful to have the 'ask chatgpt' prompt have history ala other command windows in vs code.

**Comment by barnesoir** [comment]
Please checkout the latest version to address all your points :smile:
