### ISSUE TITLE
The ChatGPT-vscode plugin won't let me re-enter my token information after I got it wrong

### ISSUE THREAD

**Issue by JediWebServices** [barnesoir/chatgpt-vscode-plugin#30]
Hello. I believe I put in the wrong info with one of the 3 requests.

- Secure-next-auth.session-token
- cl_clearance
- user-agent

When I type in the chatbox field it just gives me a spinning wheel and the box doesn't pop back up that would allow me to reset my token, clearance, and user-agent. 

I tried logging out of Visual Studio Code and back in.
I tried uninstalling and reinstalling the ChatGPT VSCode Plugin.

Yet, the issue still persists. 
Do you have any advise for me?

**Comment by CodeMilo-py** [comment]
same issue

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.
