### ISSUE TITLE
Error when copying the value for "user-agent" from Firefox "Header Request"

### ISSUE THREAD

**Issue by renko80** [barnesoir/chatgpt-vscode-plugin#32]
Hi, 

I am trying to follow the steps of the tutorial @barnesoir  left us,   but I found a little bit  to fullfill it . I miss more graphical indications.

I am stucked in the step:

"3.-Copy the value for user-agent from the Request Headers and enter it into the prompt."

Is it supposed that we have to copy the value :    Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0

![image](https://user-images.githubusercontent.com/120383335/210420456-abb33029-9637-4b0f-8f0d-021c11e5d3e5.png)

in the prompt??

If possitive nothing happens 

Thanks in advance

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.
