### ISSUE TITLE
Error sending request to ChatGPT

### ISSUE THREAD

**Issue by cjmaret** [barnesoir/chatgpt-vscode-plugin#33]
Upon trying to make a ChatGPT request (like "explain this code"), I get an error that reads "Error sending request to ChatGPT; ChatGPT failed to refresh auth token. Error: 403 Forbidden".

I've added the correct auth token, clearance token, and user-agent value more than 5 times, on Firefox, and with NPM version 19.

I'm not sure what else I could be doing to make this work.

<img width="483" alt="Screenshot 2023-01-08 at 12 24 04" src="https://user-images.githubusercontent.com/77926563/211210043-2307ff71-1f75-482c-abc6-9df44b7a31da.png">

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.

**Comment by enydrueda** [comment]
How can I use the official API?, how can I re-ingress the credentials?
