### ISSUE TITLE
it dosen't work, just "thinking..."

### ISSUE THREAD

**Issue by jiuyuanlvbu** [barnesoir/chatgpt-vscode-plugin#35]
It worked properly last night, it suddenly does not work now.
![image](https://user-images.githubusercontent.com/51329311/217468090-c14c8465-9164-4a43-ac97-1ef5cfc0ccd8.png)

by the way, I don't have the command "_ChatGPT: Reset token_".（）
![image](https://user-images.githubusercontent.com/51329311/217468576-6e6699a2-bb6b-4aff-868b-45ae51b895b3.png)
![image](https://user-images.githubusercontent.com/51329311/217468822-39d10c07-a6e5-4adc-8837-3b02a2394212.png)

Information:
ChatGPT: v3.5.6
Vs Code: Latest
windows 10 20H2 19042.1586

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.
