### ISSUE TITLE
Error sending request to chatGPT

### ISSUE THREAD

**Issue by satishsalesforce** [barnesoir/chatgpt-vscode-plugin#36]
Hi Team thanks and good day I tried to run the extension. by cloning the close and given all the session key, clearance and browser agent. when I am asking any questions it throws error. attached screenshot.
<img width="1791" alt="Screenshot 2023-02-12 at 08 27 27" src="https://user-images.githubusercontent.com/118750862/218300764-cc69f786-c7f2-49c6-857d-195ffb879fd2.png">

**Comment by barnesoir** [comment]
Fixed using official API in v2 release.
