### ISSUE TITLE
No contextualization

### ISSUE THREAD

**Issue by Marvelousp4** [barnesoir/chatgpt-vscode-plugin#8]
![image](https://user-images.githubusercontent.com/50507788/206076178-1defa742-eb22-465b-891c-6d97b7ffd22b.png)

**Comment by barnesoir** [comment]
Can you provide more details, with a full list of commands and code selection

**Comment by Marvelousp4** [comment]
On the web page:
![image](https://user-images.githubusercontent.com/50507788/206078979-8d6f83e5-4059-4415-ae71-de528d252d5e.png)

In vscode:
![image](https://user-images.githubusercontent.com/50507788/206079026-003a99ba-64e3-44cc-8094-182944f94ecd.png)
